// Generated by CoffeeScript 1.9.1
(function() {
  QUnit.test('Manual', function(assert) {
    // var done;
    // done = assert.async();
    return $.ajax({
      type: "GET",
      dataType: "json",
      url: "test.json",
      cache: false
    }).done(function() {
      return $.ajax({
        type: "GET",
        dataType: "json",
        url: "test.json",
        cache: false
      }).done(function() {
        assert.ok(true);
        // return done();
      });
    });

    // return
  });

}).call(this);
